import { Inter } from "next/font/google";
import "./globals.css";
import "./custom.css";
import Header from "@/components/root/Header";
import Footer from "@/components/root/Footer";
import Slider from "@/components/root/slider";
import 'bootstrap-icons/font/bootstrap-icons.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"h-screen"}>
        <Header />
        <Slider />
        {children}
        <Footer />
      </body>
    </html>
  );
}
